name = "yt-stats"
main = "src/index.ts"
compatibility_date = "2024-05-29"

[triggers]
crons = ["0 9 * * 1"] # Every Monday at 9:00 AM UTC

[[kv_namespaces]]
binding = "YT_CACHE"
id = "5ba27951c7594ec4ab4e5658edcfb56c" # User will need to replace this

[vars]
ALLOWED_ORIGIN = "*" # Ideally "https://zmrfzn.pages.dev", but * for dev/preview
